name: Validation of cicd_example
on: [push]

jobs:
  run-all:
    runs-on: windows-latest
    name: Run MSBuild
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicdtest  # Artifact name
          path: ./cicdtest/bin/Debug/cicdtest.exe   # Files or folder to upload
      
